SET NAMES utf8mb4;

ALTER TABLE `world_config`
  MODIFY COLUMN `realm_id` int(11) UNSIGNED NOT NULL COMMENT '服务器ID（对应 realmlist.id）',
  MODIFY COLUMN `compression` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '网络压缩等级',
  MODIFY COLUMN `login_queue_grace_period_secs` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '登录排队宽限时间（秒）',
  MODIFY COLUMN `character_screen_max_idle_time` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '角色选择界面最大空闲时间（秒）',
  MODIFY COLUMN `player_hard_limit` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '玩家在线硬上限',
  MODIFY COLUMN `antiflood_sanction` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '防刷屏处罚方式',
  MODIFY COLUMN `packet_bcast_threads` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '封包广播线程数',
  MODIFY COLUMN `packet_bcast_frequency` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '封包广播频率',
  MODIFY COLUMN `mailspam_expire_secs` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '邮件防刷记录过期时间（秒）',
  MODIFY COLUMN `mailspam_max_mails` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '邮件防刷最大邮件数',
  MODIFY COLUMN `mailspam_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '邮件发送最低等级',
  MODIFY COLUMN `mailspam_account_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '邮件发送最低账号安全等级',
  MODIFY COLUMN `mailspam_money` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '邮件发送最低携带金币',
  MODIFY COLUMN `empty_maps_update_time` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '空地图更新周期',
  MODIFY COLUMN `cod_force_tag_max_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'COD强制标记最大等级',
  MODIFY COLUMN `pub_chans_mute_vanish_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '公共频道禁言消失等级',
  MODIFY COLUMN `gmtickets_admin_security` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：GM工单管理安全',
  MODIFY COLUMN `gmtickets_minlevel` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：GM工单minlevel',
  MODIFY COLUMN `battleground_queues_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '战场队列数量',
  MODIFY COLUMN `corpses_update_minutes` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '尸体更新（分钟）',
  MODIFY COLUMN `bones_expire_minutes` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '骨骸过期（分钟）',
  MODIFY COLUMN `async_tasks_threads_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '异步任务线程数数量',
  MODIFY COLUMN `av_min_players_in_queue` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AV最小玩家IN队列',
  MODIFY COLUMN `av_initial_max_players` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AV初始最大玩家',
  MODIFY COLUMN `inactive_players_skip_updates` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：非活跃玩家跳过更新',
  MODIFY COLUMN `item_instantsave_quality` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '物品即时保存品质',
  MODIFY COLUMN `item_rareloot_quality` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '物品稀有掉落品质',
  MODIFY COLUMN `whisp_diff_zone_min_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '密语差值地区最小等级',
  MODIFY COLUMN `channel_invite_min_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '频道邀请最小等级',
  MODIFY COLUMN `world_chan_min_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '世界频道最小等级',
  MODIFY COLUMN `world_chan_cd` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：世界频道冷却',
  MODIFY COLUMN `world_chan_cd_max_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '世界频道冷却最大等级',
  MODIFY COLUMN `world_chan_cd_scaling` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：世界频道冷却缩放',
  MODIFY COLUMN `world_chan_cd_use_account_max_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '世界频道冷却使用账号最大等级',
  MODIFY COLUMN `say_emote_min_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '说话表情最小等级',
  MODIFY COLUMN `say_min_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '说话最小等级',
  MODIFY COLUMN `yell_min_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '喊话最小等级',
  MODIFY COLUMN `yellrange_min` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：喊话范围最小',
  MODIFY COLUMN `whisper_targets_max` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：密语目标最大',
  MODIFY COLUMN `whisper_targets_bypass_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '密语目标绕过等级',
  MODIFY COLUMN `whisper_targets_decay` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：密语目标衰减',
  MODIFY COLUMN `yellrange_linearscale_maxlevel` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：喊话范围线性缩放maxlevel',
  MODIFY COLUMN `yellrange_quadraticscale_maxlevel` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：喊话范围二次缩放maxlevel',
  MODIFY COLUMN `dyn_respawn_players_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '动态重生玩家阈值',
  MODIFY COLUMN `dyn_respawn_players_leveldiff` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：动态重生玩家leveldiff',
  MODIFY COLUMN `dyn_respawn_min_respawn_time` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '动态重生最小重生时间',
  MODIFY COLUMN `dyn_respawn_min_respawn_time_elite` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：动态重生最小重生时间精英',
  MODIFY COLUMN `dyn_respawn_min_respawn_time_indoors` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：动态重生最小重生时间室内',
  MODIFY COLUMN `dyn_respawn_affect_respawn_time_below` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：动态重生影响重生时间低于',
  MODIFY COLUMN `dyn_respawn_affect_level_below` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：动态重生影响等级低于',
  MODIFY COLUMN `mtcells_threads` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：多线程Cell线程数',
  MODIFY COLUMN `mtcells_safedistance` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：多线程Cell安全距离',
  MODIFY COLUMN `mapupdate_instanced_update_threads` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：地图更新副本更新线程数',
  MODIFY COLUMN `mapupdate_update_packets_diff` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：地图更新更新封包差值',
  MODIFY COLUMN `mapupdate_update_players_diff` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：地图更新更新玩家差值',
  MODIFY COLUMN `mapupdate_update_cells_diff` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：地图更新更新Cell差值',
  MODIFY COLUMN `log_money_trades_treshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：日志金币交易阈值',
  MODIFY COLUMN `relocation_vmap_check_timer` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：重定位VMap检查计时器',
  MODIFY COLUMN `mapupdate_tick_lower_visibility_distance` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '地图更新周期降低可视距离距离',
  MODIFY COLUMN `mapupdate_tick_increase_visibility_distance` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '地图更新周期提升可视距离距离',
  MODIFY COLUMN `mapupdate_min_visibility_distance` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '地图更新最小可视距离距离',
  MODIFY COLUMN `mapupdate_tick_lower_grid_activation_distance` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '地图更新周期降低Grid激活距离',
  MODIFY COLUMN `mapupdate_tick_increase_grid_activation_distance` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '地图更新周期提升Grid激活距离',
  MODIFY COLUMN `pbcast_diff_lower_visibility_distance` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '广播差值降低可视距离距离',
  MODIFY COLUMN `mapupdate_min_grid_activation_distance` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '地图更新最小Grid激活距离',
  MODIFY COLUMN `continents_motionupdate_threads` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：大陆motionupdate线程数',
  MODIFY COLUMN `perflog_slow_world_update` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：性能日志慢世界更新',
  MODIFY COLUMN `perflog_slow_map_update` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：性能日志慢MAP更新',
  MODIFY COLUMN `perflog_slow_mapsystem_update` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：性能日志慢地图系统更新',
  MODIFY COLUMN `perflog_slow_sessions_update` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：性能日志慢会话更新',
  MODIFY COLUMN `perflog_slow_unique_session_update` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：性能日志慢单个session更新',
  MODIFY COLUMN `perflog_slow_async_queries` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：性能日志慢异步查询',
  MODIFY COLUMN `perflog_slow_packet` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：性能日志慢封包',
  MODIFY COLUMN `perflog_slow_map_packets` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：性能日志慢MAP封包',
  MODIFY COLUMN `perflog_slow_packet_bcast` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：性能日志慢封包广播',
  MODIFY COLUMN `async_queries_tick_timeout` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '异步查询周期超时',
  MODIFY COLUMN `login_per_tick` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：登录每周期',
  MODIFY COLUMN `anticrash_rearm_timer` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：防崩溃重新触发计时器',
  MODIFY COLUMN `anticrash_options` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：防崩溃选项',
  MODIFY COLUMN `max_points_per_mvt_packet` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：最大点数每移动封包',
  MODIFY COLUMN `debuff_limit` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：减益限制',
  MODIFY COLUMN `spells_ccdelay` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：法术控制延迟',
  MODIFY COLUMN `pet_default_loyalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：宠物默认忠诚',
  MODIFY COLUMN `map_objectsupdate_threads` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：MAPobjectsupdate线程数',
  MODIFY COLUMN `map_objectsupdate_timeout` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'MAPobjectsupdate超时',
  MODIFY COLUMN `map_visibilityupdate_threads` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：MAPvisibilityupdate线程数',
  MODIFY COLUMN `map_visibilityupdate_timeout` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'MAPvisibilityupdate超时',
  MODIFY COLUMN `interval_save` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '角色保存间隔（毫秒）',
  MODIFY COLUMN `interval_gridclean` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Grid清理间隔（毫秒）',
  MODIFY COLUMN `interval_mapupdate` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '地图更新间隔（毫秒）',
  MODIFY COLUMN `interval_changeweather` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '天气变化间隔（毫秒）',
  MODIFY COLUMN `port_world` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '世界服监听端口',
  MODIFY COLUMN `game_type` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '服务器类型',
  MODIFY COLUMN `realm_zone` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '服务器地区',
  MODIFY COLUMN `strict_player_names` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否严格校验玩家名称',
  MODIFY COLUMN `strict_charter_names` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否严格校验公会章程名称',
  MODIFY COLUMN `strict_pet_names` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否严格校验宠物名称',
  MODIFY COLUMN `min_player_name` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '玩家名称最小长度',
  MODIFY COLUMN `min_charter_name` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '公会章程名称最小长度',
  MODIFY COLUMN `min_pet_name` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '宠物名称最小长度',
  MODIFY COLUMN `characters_creating_disabled` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否禁用创建角色',
  MODIFY COLUMN `characters_per_account` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '每个账号可创建角色上限',
  MODIFY COLUMN `characters_per_realm` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '每个服务器可创建角色上限',
  MODIFY COLUMN `skip_cinematics` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '跳过过场动画模式',
  MODIFY COLUMN `max_player_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '玩家最大等级',
  MODIFY COLUMN `start_player_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '新角色初始等级',
  MODIFY COLUMN `start_player_money` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '新角色初始铜币',
  MODIFY COLUMN `max_honor_points` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大荣誉点数',
  MODIFY COLUMN `start_honor_points` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '初始荣誉点数',
  MODIFY COLUMN `min_honor_kills` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '荣誉击杀最小计数',
  MODIFY COLUMN `instance_reset_time_hour` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '副本重置时间点（小时）',
  MODIFY COLUMN `instance_unload_delay` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '副本卸载延迟',
  MODIFY COLUMN `max_spell_casts_in_chain` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '连续施法最大次数',
  MODIFY COLUMN `max_primary_trade_skill` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '主专业技能最大数量',
  MODIFY COLUMN `min_petition_signs` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '公会/队伍请愿最少签名数',
  MODIFY COLUMN `gm_login_state` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'GM登录状态',
  MODIFY COLUMN `gm_visible_state` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'GM可见状态',
  MODIFY COLUMN `gm_accept_tickets` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'GM是否接收工单',
  MODIFY COLUMN `gm_chat` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'GM聊天状态',
  MODIFY COLUMN `gm_wispering_to` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'GM密语权限状态',
  MODIFY COLUMN `gm_level_in_gm_list` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '显示在GM列表中的最低GM等级',
  MODIFY COLUMN `gm_level_in_who_list` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '显示在who列表中的最低GM等级',
  MODIFY COLUMN `start_gm_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '初始GM等级',
  MODIFY COLUMN `group_visibility` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '队伍可见性模式',
  MODIFY COLUMN `mail_delivery_delay` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '邮件投递延迟（秒）',
  MODIFY COLUMN `mass_mailer_send_per_tick` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '批量发信每个周期发送数量',
  MODIFY COLUMN `mail_max_per_hour` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '每小时最大邮件数',
  MODIFY COLUMN `uptime_update` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '在线时长写库间隔（毫秒）',
  MODIFY COLUMN `auction_deposit_min` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '拍卖最低押金',
  MODIFY COLUMN `skill_chance_orange` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：技能chance橙色',
  MODIFY COLUMN `skill_chance_yellow` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：技能chance黄色',
  MODIFY COLUMN `skill_chance_green` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：技能chance绿色',
  MODIFY COLUMN `skill_chance_grey` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：技能chance灰色',
  MODIFY COLUMN `skill_chance_mining_steps` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：技能chance采矿steps',
  MODIFY COLUMN `skill_chance_skinning_steps` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：技能chance剥皮steps',
  MODIFY COLUMN `skill_gain_crafting` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：技能提升制造',
  MODIFY COLUMN `skill_gain_defense` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：技能提升防御',
  MODIFY COLUMN `skill_gain_gathering` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：技能提升采集',
  MODIFY COLUMN `skill_gain_weapon` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：技能提升武器',
  MODIFY COLUMN `max_overspeed_pings` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大超速Ping容忍次数',
  MODIFY COLUMN `chatflood_message_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '聊天刷屏消息数量阈值',
  MODIFY COLUMN `chatflood_message_delay` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '聊天刷屏消息间隔阈值',
  MODIFY COLUMN `chatflood_mute_time` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '聊天刷屏禁言时间',
  MODIFY COLUMN `creature_family_assistance_delay` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '生物家族援助延迟',
  MODIFY COLUMN `creature_family_flee_delay` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '生物家族逃跑延迟',
  MODIFY COLUMN `world_boss_level_diff` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '世界Boss等级差限制',
  MODIFY COLUMN `chat_strict_link_checking_severity` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：聊天严格链接检查严格度',
  MODIFY COLUMN `chat_strict_link_checking_kick` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：聊天严格链接检查踢下线',
  MODIFY COLUMN `corpse_decay_normal` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：corpse衰减普通',
  MODIFY COLUMN `corpse_decay_rare` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：corpse衰减稀有',
  MODIFY COLUMN `corpse_decay_elite` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：corpse衰减精英',
  MODIFY COLUMN `corpse_decay_rareelite` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：corpse衰减稀有精英',
  MODIFY COLUMN `corpse_decay_worldboss` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：corpse衰减世界Boss',
  MODIFY COLUMN `instant_logout` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否允许瞬间下线',
  MODIFY COLUMN `battleground_invitation_type` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '战场邀请类型',
  MODIFY COLUMN `battleground_premade_queue_group_min_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '战场预组队列队伍最小大小',
  MODIFY COLUMN `battleground_premature_finish_timer` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：战场提前结束计时器',
  MODIFY COLUMN `battleground_premade_group_wait_for_match` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：战场预组队伍等待FOR匹配',
  MODIFY COLUMN `battleground_queue_announcer_join` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：战场队列announcer加入',
  MODIFY COLUMN `group_offline_leader_delay` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '队长离线转移延迟',
  MODIFY COLUMN `guild_event_log_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '公会事件日志条数',
  MODIFY COLUMN `mirrortimer_fatigue_max` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：mirrortimer疲劳最大',
  MODIFY COLUMN `mirrortimer_breath_max` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：mirrortimer呼吸最大',
  MODIFY COLUMN `mirrortimer_environmental_max` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：mirrortimer环境最大',
  MODIFY COLUMN `environmental_damage_min` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：环境伤害最小',
  MODIFY COLUMN `environmental_damage_max` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：环境伤害最大',
  MODIFY COLUMN `min_level_stat_save` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：最小等级stat保存',
  MODIFY COLUMN `maintenance_day` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '每周维护日',
  MODIFY COLUMN `chardelete_keep_days` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '角色删除保留天数',
  MODIFY COLUMN `chardelete_method` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '角色删除方式',
  MODIFY COLUMN `chardelete_min_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '角色删除最低等级限制',
  MODIFY COLUMN `guid_reserve_size_creature` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '生物GUID预留数量',
  MODIFY COLUMN `guid_reserve_size_gameobject` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '游戏对象GUID预留数量',
  MODIFY COLUMN `respec_base_cost` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '洗天赋基础费用',
  MODIFY COLUMN `respec_multiplicative_cost` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '洗天赋递增费用倍率',
  MODIFY COLUMN `respec_min_multiplier` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '洗天赋最小倍率',
  MODIFY COLUMN `respec_max_multiplier` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '洗天赋最大倍率',
  MODIFY COLUMN `battleground_group_limit` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '战场组队人数上限',
  MODIFY COLUMN `creature_summon_limit` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '生物召唤上限',
  MODIFY COLUMN `war_effort_autocomplete_period` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '开门物资自动完成周期',
  MODIFY COLUMN `account_concurrent_auction_limit` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '账号并发拍卖上限',
  MODIFY COLUMN `banlist_reload_timer` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '封禁列表重载间隔（秒）',
  MODIFY COLUMN `autobroadcast_interval` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '自动广播间隔（秒）',
  MODIFY COLUMN `transmog_req_item` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '幻化所需物品ID',
  MODIFY COLUMN `transmog_req_item_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '幻化所需物品数量',
  MODIFY COLUMN `ac_movement_ban_duration` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动封禁时长',
  MODIFY COLUMN `ac_movement_cheat_reverse_time_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊逆向时间阈值',
  MODIFY COLUMN `ac_movement_cheat_reverse_time_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊逆向时间惩罚',
  MODIFY COLUMN `ac_movement_cheat_null_time_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊空值时间阈值',
  MODIFY COLUMN `ac_movement_cheat_null_time_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊空值时间惩罚',
  MODIFY COLUMN `ac_movement_cheat_skipped_heartbeats_threshold_tick` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊跳过心跳阈值周期',
  MODIFY COLUMN `ac_movement_cheat_skipped_heartbeats_threshold_total` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊跳过心跳阈值总数',
  MODIFY COLUMN `ac_movement_cheat_skipped_heartbeats_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊跳过心跳惩罚',
  MODIFY COLUMN `ac_movement_cheat_time_desync_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊时间不同步阈值',
  MODIFY COLUMN `ac_movement_cheat_time_desync_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊时间不同步惩罚',
  MODIFY COLUMN `ac_movement_cheat_num_desyncs_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊次数desyncs阈值',
  MODIFY COLUMN `ac_movement_cheat_num_desyncs_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊次数desyncs惩罚',
  MODIFY COLUMN `ac_movement_cheat_overspeed_distance_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊超速distance阈值',
  MODIFY COLUMN `ac_movement_cheat_overspeed_distance_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊超速distance惩罚',
  MODIFY COLUMN `ac_movement_cheat_overspeed_jump_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊超速跳跃阈值',
  MODIFY COLUMN `ac_movement_cheat_overspeed_jump_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊超速跳跃惩罚',
  MODIFY COLUMN `ac_movement_cheat_jump_speed_change_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊跳跃speed变更阈值',
  MODIFY COLUMN `ac_movement_cheat_jump_speed_change_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊跳跃speed变更惩罚',
  MODIFY COLUMN `ac_movement_cheat_multi_jump_threshold_tick` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊多重跳跃阈值周期',
  MODIFY COLUMN `ac_movement_cheat_multi_jump_threshold_total` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊多重跳跃阈值总数',
  MODIFY COLUMN `ac_movement_cheat_multi_jump_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊多重跳跃惩罚',
  MODIFY COLUMN `ac_movement_cheat_wall_climb_threshold_tick` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊墙面攀爬阈值周期',
  MODIFY COLUMN `ac_movement_cheat_wall_climb_threshold_total` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊墙面攀爬阈值总数',
  MODIFY COLUMN `ac_movement_cheat_wall_climb_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊墙面攀爬惩罚',
  MODIFY COLUMN `ac_movement_cheat_unreachable_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊不可达阈值',
  MODIFY COLUMN `ac_movement_cheat_unreachable_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊不可达惩罚',
  MODIFY COLUMN `ac_movement_cheat_fly_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊飞行阈值',
  MODIFY COLUMN `ac_movement_cheat_fly_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊飞行惩罚',
  MODIFY COLUMN `ac_movement_cheat_no_fall_time_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊不下落时间阈值',
  MODIFY COLUMN `ac_movement_cheat_no_fall_time_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊不下落时间惩罚',
  MODIFY COLUMN `ac_movement_cheat_teleport_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊传送阈值',
  MODIFY COLUMN `ac_movement_cheat_teleport_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊传送惩罚',
  MODIFY COLUMN `ac_movement_cheat_tele_to_transport_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊传送TO载具阈值',
  MODIFY COLUMN `ac_movement_cheat_tele_to_transport_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊传送TO载具惩罚',
  MODIFY COLUMN `ac_movement_cheat_fake_transport_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊伪造载具阈值',
  MODIFY COLUMN `ac_movement_cheat_fake_transport_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊伪造载具惩罚',
  MODIFY COLUMN `ac_movement_cheat_water_walk_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊水上行走阈值',
  MODIFY COLUMN `ac_movement_cheat_water_walk_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊水上行走惩罚',
  MODIFY COLUMN `ac_movement_cheat_slow_fall_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊慢下落阈值',
  MODIFY COLUMN `ac_movement_cheat_slow_fall_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊慢下落惩罚',
  MODIFY COLUMN `ac_movement_cheat_hover_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊悬浮阈值',
  MODIFY COLUMN `ac_movement_cheat_hover_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊悬浮惩罚',
  MODIFY COLUMN `ac_movement_cheat_fixed_z_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊固定Z轴阈值',
  MODIFY COLUMN `ac_movement_cheat_fixed_z_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊固定Z轴惩罚',
  MODIFY COLUMN `ac_movement_cheat_root_move_threshold_tick` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊定身move阈值周期',
  MODIFY COLUMN `ac_movement_cheat_root_move_threshold_total` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊定身move阈值总数',
  MODIFY COLUMN `ac_movement_cheat_root_move_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊定身move惩罚',
  MODIFY COLUMN `ac_movement_cheat_self_root_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊自身定身阈值',
  MODIFY COLUMN `ac_movement_cheat_self_root_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊自身定身惩罚',
  MODIFY COLUMN `ac_movement_cheat_wrong_ack_data_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊错误确认数据阈值',
  MODIFY COLUMN `ac_movement_cheat_wrong_ack_data_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊错误确认数据惩罚',
  MODIFY COLUMN `ac_movement_cheat_pending_ack_delay_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊待处理确认延迟阈值',
  MODIFY COLUMN `ac_movement_cheat_pending_ack_delay_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊待处理确认延迟惩罚',
  MODIFY COLUMN `ac_movement_cheat_explore_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊探索阈值',
  MODIFY COLUMN `ac_movement_cheat_explore_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊探索惩罚',
  MODIFY COLUMN `ac_movement_cheat_explore_high_level_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊探索高等级阈值',
  MODIFY COLUMN `ac_movement_cheat_explore_high_level_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊探索高等级惩罚',
  MODIFY COLUMN `ac_movement_cheat_forbidden_area_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊禁止区域阈值',
  MODIFY COLUMN `ac_movement_cheat_forbidden_area_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC移动作弊禁止区域惩罚',
  MODIFY COLUMN `movement_change_ack_time` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '移动变更确认时间',
  MODIFY COLUMN `ac_warden_client_response_delay` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'ACWarden客户端响应延迟',
  MODIFY COLUMN `ac_warden_client_check_holdoff` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：ACWarden客户端检查等待间隔',
  MODIFY COLUMN `ac_warden_default_penalty` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'ACWarden默认惩罚',
  MODIFY COLUMN `ac_warden_client_ban_duration` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：ACWarden客户端封禁时长',
  MODIFY COLUMN `ac_warden_num_mem_checks` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：ACWarden次数内存checks',
  MODIFY COLUMN `ac_warden_num_other_checks` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：ACWarden次数其他checks',
  MODIFY COLUMN `ac_warden_db_loglevel` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：ACWarden数据库日志等级',
  MODIFY COLUMN `ac_antispam_max_restriction_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC反垃圾最大限制等级',
  MODIFY COLUMN `ac_antispam_original_normalize_mask` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC反垃圾原始规范化掩码',
  MODIFY COLUMN `ac_antispam_fully_normalize_mask` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC反垃圾fully规范化掩码',
  MODIFY COLUMN `ac_antispam_score_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC反垃圾分数阈值',
  MODIFY COLUMN `ac_antispam_mutetime` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC反垃圾禁言时长',
  MODIFY COLUMN `ac_antispam_chat_mask` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC反垃圾聊天掩码',
  MODIFY COLUMN `ac_antispam_detect_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC反垃圾检测阈值',
  MODIFY COLUMN `ac_antispam_repeat_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC反垃圾重复数量',
  MODIFY COLUMN `ac_antispam_update_timer` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC反垃圾更新计时器',
  MODIFY COLUMN `ac_antispam_message_block_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC反垃圾消息拦截大小',
  MODIFY COLUMN `ac_antispam_frequency_time` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC反垃圾频率时间',
  MODIFY COLUMN `ac_antispam_frequency_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'AC反垃圾频率数量',
  MODIFY COLUMN `bg_sv_spark_max_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '战场SV火花最大数量',
  MODIFY COLUMN `item_log_restore_quality` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '物品恢复日志最低品质',
  MODIFY COLUMN `chat_min_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '聊天最低等级',
  MODIFY COLUMN `auto_commit_minutes` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '自动提交间隔（分钟）',
  MODIFY COLUMN `account_data_last_login_days` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '账号数据按最后登录保留天数',
  MODIFY COLUMN `password_change_reward_item` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '修改密码奖励物品ID',
  MODIFY COLUMN `max_age_show_warning` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大年龄警告阈值',
  MODIFY COLUMN `high_level_character` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '高等级角色判定阈值',
  MODIFY COLUMN `account_trusted_ip_percentage` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '账号可信IP比例阈值',
  MODIFY COLUMN `analysis_no_fingerprint_match_weight` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：分析不指纹匹配权重',
  MODIFY COLUMN `analysis_no_extended_data_match_weight` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：分析不扩展数据匹配权重',
  MODIFY COLUMN `analysis_no_cpu_data_weight` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：分析不CPU数据权重',
  MODIFY COLUMN `analysis_no_cpu_data_match_weight` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：分析不CPU数据匹配权重',
  MODIFY COLUMN `analysis_no_extended_data_weight` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：分析不扩展数据权重',
  MODIFY COLUMN `analysis_warning_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '分析系统告警阈值',
  MODIFY COLUMN `auto_restart_max_server_uptime` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '自动重启最大运行时长',
  MODIFY COLUMN `auto_restart_hour_min` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '自动重启最早小时',
  MODIFY COLUMN `auto_restart_hour_max` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '自动重启最晚小时',
  MODIFY COLUMN `diff_hc_protection` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '硬核保护等级差',
  MODIFY COLUMN `login_region_queue_level_threshold` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '区域排队等级阈值',
  MODIFY COLUMN `priority_queue_priority_per_tick` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '优先队列每周期放行数量',
  MODIFY COLUMN `priority_queue_donator_settings` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '赞助者优先队列设置模式',
  MODIFY COLUMN `priority_queue_donator_priority` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '赞助者优先级',
  MODIFY COLUMN `priority_queue_western_priority` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '西方地区优先级',
  MODIFY COLUMN `priority_queue_high_level_char` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '高等级角色优先阈值',
  MODIFY COLUMN `priority_queue_high_level_char_priority` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '高等级角色优先级',
  MODIFY COLUMN `priority_queue_priority_per_account_day` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '每账号每日优先次数',
  MODIFY COLUMN `priority_queue_priority_reduction_multibox` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '多开时优先级衰减倍率',
  MODIFY COLUMN `max_percentage_pop_non_regional` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '非本区人口占比上限',
  MODIFY COLUMN `max_percentage_pop_regional` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '本区人口占比上限',
  MODIFY COLUMN `auto_pdump_min_char_level` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '自动角色导出最低等级',
  MODIFY COLUMN `auto_pdump_delete_after_days` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '自动角色导出保留天数',
  MODIFY COLUMN `content_phase` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '内容开放阶段',
  MODIFY COLUMN `shop_refund_window` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '商城退款时间窗口',
  MODIFY COLUMN `performance_report_interval` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '性能报告输出间隔',
  MODIFY COLUMN `max_gold_transferred` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '角色转移最大金币',
  MODIFY COLUMN `max_item_stack_transferred` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '角色转移最大物品堆叠数',
  MODIFY COLUMN `dynamic_scaling_pop` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '动态缩放人口阈值',
  MODIFY COLUMN `death_sickness_level` int(11) NOT NULL DEFAULT 0 COMMENT '死亡虚弱生效等级',
  MODIFY COLUMN `quest_low_level_hide_diff` int(11) NOT NULL DEFAULT 0 COMMENT '低等级任务隐藏等级差',
  MODIFY COLUMN `quest_high_level_hide_diff` int(11) NOT NULL DEFAULT 0 COMMENT '高等级任务隐藏等级差',
  MODIFY COLUMN `ac_anticheat_max_allowed_desync` int(11) NOT NULL DEFAULT 0 COMMENT '反作弊允许最大时间不同步值',
  MODIFY COLUMN `rate_health` float NOT NULL DEFAULT 0 COMMENT '生命倍率',
  MODIFY COLUMN `max_creature_attack_radius` float NOT NULL DEFAULT 0 COMMENT '最大生物攻击半径',
  MODIFY COLUMN `max_players_stealth_detect_range` float NOT NULL DEFAULT 0 COMMENT '最大玩家潜行检测范围',
  MODIFY COLUMN `dyn_respawn_check_range` float NOT NULL DEFAULT 0 COMMENT '动态重生检查范围',
  MODIFY COLUMN `dyn_respawn_percent_per_player` float NOT NULL DEFAULT 0 COMMENT '配置项：动态重生百分比每玩家',
  MODIFY COLUMN `dyn_respawn_max_reduction_rate` float NOT NULL DEFAULT 0 COMMENT '配置项：动态重生最大reductionrate',
  MODIFY COLUMN `rate_power_mana` float NOT NULL DEFAULT 0 COMMENT '资源法力倍率',
  MODIFY COLUMN `rate_power_rage_income` float NOT NULL DEFAULT 0 COMMENT '资源怒气获取倍率',
  MODIFY COLUMN `rate_power_rage_loss` float NOT NULL DEFAULT 0 COMMENT '资源怒气消耗倍率',
  MODIFY COLUMN `rate_power_focus` float NOT NULL DEFAULT 0 COMMENT '资源集中值倍率',
  MODIFY COLUMN `rate_power_energy` float NOT NULL DEFAULT 0 COMMENT '资源能量倍率',
  MODIFY COLUMN `rate_skill_discovery` float NOT NULL DEFAULT 0 COMMENT '技能discovery倍率',
  MODIFY COLUMN `rate_drop_item_poor` float NOT NULL DEFAULT 0 COMMENT '掉落物品垃圾倍率',
  MODIFY COLUMN `rate_drop_item_normal` float NOT NULL DEFAULT 0 COMMENT '掉落物品普通倍率',
  MODIFY COLUMN `rate_drop_item_uncommon` float NOT NULL DEFAULT 0 COMMENT '掉落物品优秀倍率',
  MODIFY COLUMN `rate_drop_item_rare` float NOT NULL DEFAULT 0 COMMENT '掉落物品稀有倍率',
  MODIFY COLUMN `rate_drop_item_epic` float NOT NULL DEFAULT 0 COMMENT '掉落物品史诗倍率',
  MODIFY COLUMN `rate_drop_item_legendary` float NOT NULL DEFAULT 0 COMMENT '掉落物品传说倍率',
  MODIFY COLUMN `rate_drop_item_artifact` float NOT NULL DEFAULT 0 COMMENT '掉落物品神器倍率',
  MODIFY COLUMN `rate_drop_item_referenced` float NOT NULL DEFAULT 0 COMMENT '掉落物品引用倍率',
  MODIFY COLUMN `rate_drop_money` float NOT NULL DEFAULT 0 COMMENT '掉落金币倍率',
  MODIFY COLUMN `rate_xp_kill` float NOT NULL DEFAULT 0 COMMENT '经验kill倍率',
  MODIFY COLUMN `rate_xp_kill_elite` float NOT NULL DEFAULT 0 COMMENT '经验kill精英倍率',
  MODIFY COLUMN `rate_xp_quest` float NOT NULL DEFAULT 0 COMMENT '经验任务倍率',
  MODIFY COLUMN `rate_xp_explore` float NOT NULL DEFAULT 0 COMMENT '经验探索倍率',
  MODIFY COLUMN `rate_reputation_gain` float NOT NULL DEFAULT 0 COMMENT '声望提升倍率',
  MODIFY COLUMN `rate_reputation_lowlevel_kill` float NOT NULL DEFAULT 0 COMMENT '声望lowlevelkill倍率',
  MODIFY COLUMN `rate_reputation_lowlevel_quest` float NOT NULL DEFAULT 0 COMMENT '声望lowlevel任务倍率',
  MODIFY COLUMN `rate_creature_normal_hp` float NOT NULL DEFAULT 0 COMMENT '生物普通生命倍率',
  MODIFY COLUMN `rate_creature_elite_elite_hp` float NOT NULL DEFAULT 0 COMMENT '生物精英精英生命倍率',
  MODIFY COLUMN `rate_creature_elite_rareelite_hp` float NOT NULL DEFAULT 0 COMMENT '生物精英稀有精英生命倍率',
  MODIFY COLUMN `rate_creature_elite_worldboss_hp` float NOT NULL DEFAULT 0 COMMENT '生物精英世界Boss生命倍率',
  MODIFY COLUMN `rate_creature_elite_rare_hp` float NOT NULL DEFAULT 0 COMMENT '生物精英稀有生命倍率',
  MODIFY COLUMN `rate_creature_normal_damage` float NOT NULL DEFAULT 0 COMMENT '生物普通伤害倍率',
  MODIFY COLUMN `rate_creature_elite_elite_damage` float NOT NULL DEFAULT 0 COMMENT '生物精英精英伤害倍率',
  MODIFY COLUMN `rate_creature_elite_rareelite_damage` float NOT NULL DEFAULT 0 COMMENT '生物精英稀有精英伤害倍率',
  MODIFY COLUMN `rate_creature_elite_worldboss_damage` float NOT NULL DEFAULT 0 COMMENT '生物精英世界Boss伤害倍率',
  MODIFY COLUMN `rate_creature_elite_rare_damage` float NOT NULL DEFAULT 0 COMMENT '生物精英稀有伤害倍率',
  MODIFY COLUMN `rate_creature_normal_spelldamage` float NOT NULL DEFAULT 0 COMMENT '生物普通法术伤害倍率',
  MODIFY COLUMN `rate_creature_elite_elite_spelldamage` float NOT NULL DEFAULT 0 COMMENT '生物精英精英法术伤害倍率',
  MODIFY COLUMN `rate_creature_elite_rareelite_spelldamage` float NOT NULL DEFAULT 0 COMMENT '生物精英稀有精英法术伤害倍率',
  MODIFY COLUMN `rate_creature_elite_worldboss_spelldamage` float NOT NULL DEFAULT 0 COMMENT '生物精英世界Boss法术伤害倍率',
  MODIFY COLUMN `rate_creature_elite_rare_spelldamage` float NOT NULL DEFAULT 0 COMMENT '生物精英稀有法术伤害倍率',
  MODIFY COLUMN `rate_creature_aggro` float NOT NULL DEFAULT 0 COMMENT '生物仇恨倍率',
  MODIFY COLUMN `rate_rest_ingame` float NOT NULL DEFAULT 0 COMMENT '休息在线倍率',
  MODIFY COLUMN `rate_rest_offline_in_tavern_or_city` float NOT NULL DEFAULT 0 COMMENT '休息离线IN旅店OR主城倍率',
  MODIFY COLUMN `rate_rest_offline_in_wilderness` float NOT NULL DEFAULT 0 COMMENT '休息离线IN野外倍率',
  MODIFY COLUMN `rate_damage_fall` float NOT NULL DEFAULT 0 COMMENT '伤害下落倍率',
  MODIFY COLUMN `rate_auction_time` float NOT NULL DEFAULT 0 COMMENT '拍卖时间倍率',
  MODIFY COLUMN `rate_auction_deposit` float NOT NULL DEFAULT 0 COMMENT '拍卖押金倍率',
  MODIFY COLUMN `rate_auction_cut` float NOT NULL DEFAULT 0 COMMENT '拍卖CUT倍率',
  MODIFY COLUMN `rate_honor` float NOT NULL DEFAULT 0 COMMENT '荣誉倍率',
  MODIFY COLUMN `rate_mining_amount` float NOT NULL DEFAULT 0 COMMENT '采矿amount倍率',
  MODIFY COLUMN `rate_mining_next` float NOT NULL DEFAULT 0 COMMENT '采矿next倍率',
  MODIFY COLUMN `rate_talent` float NOT NULL DEFAULT 0 COMMENT 'talent倍率',
  MODIFY COLUMN `rate_loyalty` float NOT NULL DEFAULT 0 COMMENT '忠诚倍率',
  MODIFY COLUMN `rate_corpse_decay_looted` float NOT NULL DEFAULT 0 COMMENT 'corpse衰减looted倍率',
  MODIFY COLUMN `rate_instance_reset_time` float NOT NULL DEFAULT 0 COMMENT '副本重置时间倍率',
  MODIFY COLUMN `rate_target_pos_recalculation_range` float NOT NULL DEFAULT 0 COMMENT '目标位置重算范围倍率',
  MODIFY COLUMN `rate_durability_loss_damage` float NOT NULL DEFAULT 0 COMMENT '耐久消耗伤害倍率',
  MODIFY COLUMN `rate_durability_loss_parry` float NOT NULL DEFAULT 0 COMMENT '耐久消耗招架倍率',
  MODIFY COLUMN `rate_durability_loss_absorb` float NOT NULL DEFAULT 0 COMMENT '耐久消耗吸收倍率',
  MODIFY COLUMN `rate_durability_loss_block` float NOT NULL DEFAULT 0 COMMENT '耐久消耗拦截倍率',
  MODIFY COLUMN `listen_range_say` float NOT NULL DEFAULT 0 COMMENT '配置项：监听范围说话',
  MODIFY COLUMN `listen_range_yell` float NOT NULL DEFAULT 0 COMMENT '配置项：监听范围喊话',
  MODIFY COLUMN `listen_range_textemote` float NOT NULL DEFAULT 0 COMMENT '配置项：监听范围文字表情',
  MODIFY COLUMN `creature_family_flee_assistance_radius` float NOT NULL DEFAULT 0 COMMENT '生物家族逃跑援助半径',
  MODIFY COLUMN `creature_family_assistance_radius` float NOT NULL DEFAULT 0 COMMENT '生物家族援助半径',
  MODIFY COLUMN `group_xp_distance` float NOT NULL DEFAULT 0 COMMENT '队伍经验距离',
  MODIFY COLUMN `threat_radius` float NOT NULL DEFAULT 0 COMMENT '仇恨半径',
  MODIFY COLUMN `ghost_run_speed_world` float NOT NULL DEFAULT 0 COMMENT '配置项：灵魂跑尸speed世界',
  MODIFY COLUMN `ghost_run_speed_bg` float NOT NULL DEFAULT 0 COMMENT '配置项：灵魂跑尸speed战场',
  MODIFY COLUMN `rate_war_effort_resource` float NOT NULL DEFAULT 0 COMMENT '战争物资resource倍率',
  MODIFY COLUMN `transmog_req_money_rate` float NOT NULL DEFAULT 0 COMMENT '配置项：幻化需求金币rate',
  MODIFY COLUMN `ac_movement_cheat_teleport_distance` float NOT NULL DEFAULT 0 COMMENT 'AC移动作弊传送距离',
  MODIFY COLUMN `ac_movement_cheat_wall_climb_angle` float NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊墙面攀爬angle',
  MODIFY COLUMN `battleground_reputation_rate_av` float NOT NULL DEFAULT 0 COMMENT '配置项：战场声望rateAV',
  MODIFY COLUMN `battleground_reputation_rate_ws` float NOT NULL DEFAULT 0 COMMENT '配置项：战场声望rateWS',
  MODIFY COLUMN `battleground_reputation_rate_ab` float NOT NULL DEFAULT 0 COMMENT '配置项：战场声望rateAB',
  MODIFY COLUMN `battleground_reputation_rate_sv` float NOT NULL DEFAULT 0 COMMENT '配置项：战场声望rateSV',
  MODIFY COLUMN `battleground_honor_rate_av` float NOT NULL DEFAULT 0 COMMENT '配置项：战场荣誉rateAV',
  MODIFY COLUMN `battleground_honor_rate_ws` float NOT NULL DEFAULT 0 COMMENT '配置项：战场荣誉rateWS',
  MODIFY COLUMN `battleground_honor_rate_ab` float NOT NULL DEFAULT 0 COMMENT '配置项：战场荣誉rateAB',
  MODIFY COLUMN `battleground_honor_rate_sv` float NOT NULL DEFAULT 0 COMMENT '配置项：战场荣誉rateSV',
  MODIFY COLUMN `suspicious_movementspeed_report_threshold` float NOT NULL DEFAULT 0 COMMENT '可疑movementspeed报告阈值',
  MODIFY COLUMN `max_faction_imbalance` float NOT NULL DEFAULT 0 COMMENT '配置项：最大阵营失衡',
  MODIFY COLUMN `open_world_honor_multiplier` float NOT NULL DEFAULT 0 COMMENT '配置项：开放世界荣誉倍率',
  MODIFY COLUMN `grid_unload` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用Grid卸载',
  MODIFY COLUMN `object_health_value_show` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否显示对象生命值',
  MODIFY COLUMN `gms_allow_public_channels` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'GM是否允许加入公共频道',
  MODIFY COLUMN `gmtickets_enable` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用GM工单系统',
  MODIFY COLUMN `tag_in_battlegrounds` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否允许战场内标记',
  MODIFY COLUMN `continents_instanciate` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否实例化大陆地图',
  MODIFY COLUMN `gm_join_opposite_faction_channels` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'GM是否可加入敌对阵营频道',
  MODIFY COLUMN `gm_allow_trades` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'GM是否允许交易',
  MODIFY COLUMN `die_command_credit` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '死亡命令是否计入击杀归属',
  MODIFY COLUMN `terrain_preload_continents` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否预加载大陆地形',
  MODIFY COLUMN `terrain_preload_instances` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否预加载副本地形',
  MODIFY COLUMN `cleanup_terrain` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否清理地形缓存',
  MODIFY COLUMN `outdoorpvp_ep_enable` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用东瘟疫之地野外PvP',
  MODIFY COLUMN `outdoorpvp_si_enable` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用希利苏斯野外PvP',
  MODIFY COLUMN `mmap_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用MMap寻路',
  MODIFY COLUMN `player_commands` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用玩家命令',
  MODIFY COLUMN `save_respawn_time_immediately` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否立即保存重生时间',
  MODIFY COLUMN `allow_two_side_accounts` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否允许双阵营角色共存',
  MODIFY COLUMN `allow_two_side_interaction_chat` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否允许双阵营聊天',
  MODIFY COLUMN `allow_two_side_interaction_channel` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否允许双阵营频道互动',
  MODIFY COLUMN `allow_two_side_interaction_group` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否允许双阵营组队',
  MODIFY COLUMN `allow_two_side_interaction_guild` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否允许双阵营公会互动',
  MODIFY COLUMN `allow_two_side_interaction_trade` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否允许双阵营交易',
  MODIFY COLUMN `allow_two_side_interaction_auction` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否允许双阵营拍卖行互通',
  MODIFY COLUMN `allow_two_side_interaction_mail` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否允许双阵营邮件互通',
  MODIFY COLUMN `allow_two_side_who_list` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否允许双阵营who列表互通',
  MODIFY COLUMN `allow_two_side_add_friend` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否允许双阵营添加好友',
  MODIFY COLUMN `instance_ignore_level` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '副本是否忽略等级限制',
  MODIFY COLUMN `instance_ignore_raid` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '副本是否忽略团队限制',
  MODIFY COLUMN `cast_unstuck` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否允许施放卡点自救',
  MODIFY COLUMN `gm_log_trade` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否记录GM交易日志',
  MODIFY COLUMN `gm_lower_security` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否允许GM降低安全限制',
  MODIFY COLUMN `always_max_skill_for_level` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否始终按等级给予最大技能值',
  MODIFY COLUMN `weather` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用天气系统',
  MODIFY COLUMN `event_announce` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用事件公告',
  MODIFY COLUMN `quest_ignore_raid` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '任务是否忽略团队限制',
  MODIFY COLUMN `detect_pos_collision` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否检测位置碰撞',
  MODIFY COLUMN `restricted_lfg_channel` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否限制组队频道',
  MODIFY COLUMN `silently_gm_join_to_channel` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'GM加入频道时是否静默',
  MODIFY COLUMN `strict_latin_in_general_channels` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '综合频道是否严格限制拉丁字符',
  MODIFY COLUMN `chat_fake_message_preventing` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否防止伪造聊天消息',
  MODIFY COLUMN `addon_channel` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用插件频道',
  MODIFY COLUMN `corpse_empty_loot_show` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '空尸体是否显示可拾取',
  MODIFY COLUMN `death_corpse_reclaim_delay_pvp` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'PvP死亡是否启用尸体取回延迟',
  MODIFY COLUMN `death_corpse_reclaim_delay_pve` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'PvE死亡是否启用尸体取回延迟',
  MODIFY COLUMN `death_bones_world` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '世界地图死亡是否生成骨骸',
  MODIFY COLUMN `death_bones_bg` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '战场死亡是否生成骨骸',
  MODIFY COLUMN `all_taxi_paths` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否解锁所有飞行点',
  MODIFY COLUMN `skill_fail_loot_fishing` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '钓鱼失败是否仍可获得战利品',
  MODIFY COLUMN `skill_fail_gain_fishing` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '钓鱼失败是否仍可提升技能',
  MODIFY COLUMN `skill_fail_possible_fishingpool` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '钓鱼失败时是否可能判定鱼群',
  MODIFY COLUMN `battleground_cast_deserter` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否对战场逃离者施加逃亡者Debuff',
  MODIFY COLUMN `battleground_queue_announcer_start` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用战场开局队列公告',
  MODIFY COLUMN `kick_player_on_bad_packet` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '异常封包是否踢下线',
  MODIFY COLUMN `pet_los` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '宠物是否检测视线',
  MODIFY COLUMN `stats_save_only_on_logout` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否仅在下线时保存属性',
  MODIFY COLUMN `clean_character_db` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否清理角色数据库',
  MODIFY COLUMN `vmap_indoor_check` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'VMap是否启用室内检测',
  MODIFY COLUMN `pet_unsummon_at_mount` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '上坐骑时是否自动收回宠物',
  MODIFY COLUMN `enable_dk` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用死亡骑士',
  MODIFY COLUMN `enable_movement_extrapolation_player` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用玩家移动预测',
  MODIFY COLUMN `enable_movement_extrapolation_pet` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用宠物移动预测',
  MODIFY COLUMN `whisper_restriction` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用密语限制',
  MODIFY COLUMN `mailspam_item` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '邮件防刷是否检查物品',
  MODIFY COLUMN `accurate_pvp_equip_requirements` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用准确PvP装备需求',
  MODIFY COLUMN `accurate_pvp_purchase_requirements` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用准确PvP购买需求',
  MODIFY COLUMN `accurate_pvp_timeline` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用准确PvP时间线',
  MODIFY COLUMN `accurate_pvp_rewards` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用准确PvP奖励',
  MODIFY COLUMN `battleground_randomize` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否随机化战场',
  MODIFY COLUMN `enable_crossfaction_battlegrounds` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用跨阵营战场',
  MODIFY COLUMN `enable_gear_rating_queue` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用装备评分队列',
  MODIFY COLUMN `send_loot_roll_upon_reconnect` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '重连后是否补发Roll点信息',
  MODIFY COLUMN `accurate_pets` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用准确宠物机制',
  MODIFY COLUMN `accurate_spell_effects` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用准确法术效果',
  MODIFY COLUMN `accurate_pve_events` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用准确PVE事件',
  MODIFY COLUMN `accurate_lfg` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用准确LFG机制',
  MODIFY COLUMN `no_respec_price_decay` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '洗天赋价格是否不衰减',
  MODIFY COLUMN `no_quest_xp_to_gold` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '任务经验是否不转换为金币',
  MODIFY COLUMN `auto_honor_restart` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否自动重置荣誉系统',
  MODIFY COLUMN `restore_deleted_items` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否允许恢复已删除物品',
  MODIFY COLUMN `unlinked_auction_houses` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否拆分拍卖行联通',
  MODIFY COLUMN `prevent_item_datamining` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否阻止物品数据挖掘',
  MODIFY COLUMN `transmog_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用幻化系统',
  MODIFY COLUMN `static_object_los` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '静态对象是否检测视线',
  MODIFY COLUMN `dual_spec` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用双天赋',
  MODIFY COLUMN `hardcore_disable_duel` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '硬核模式是否禁用决斗',
  MODIFY COLUMN `ac_movement_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用移动反作弊',
  MODIFY COLUMN `ac_movement_players_only` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '移动反作弊是否仅检查玩家',
  MODIFY COLUMN `ac_movement_notify_cheaters` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否通知作弊玩家被检测',
  MODIFY COLUMN `ac_movement_log_data` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否记录移动反作弊日志数据',
  MODIFY COLUMN `ac_movement_cheat_reverse_time_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊逆向时间',
  MODIFY COLUMN `ac_movement_cheat_null_time_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊空值时间',
  MODIFY COLUMN `ac_movement_cheat_skipped_heartbeats_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊跳过心跳',
  MODIFY COLUMN `ac_movement_cheat_time_desync_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊时间不同步',
  MODIFY COLUMN `ac_movement_cheat_num_desyncs_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊次数desyncs',
  MODIFY COLUMN `ac_movement_cheat_speed_hack_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊speedhack',
  MODIFY COLUMN `ac_movement_cheat_overspeed_distance_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊超速distance',
  MODIFY COLUMN `ac_movement_cheat_overspeed_jump_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊超速跳跃',
  MODIFY COLUMN `ac_movement_cheat_overspeed_jump_reject` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊超速跳跃reject',
  MODIFY COLUMN `ac_movement_cheat_jump_speed_change_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊跳跃speed变更',
  MODIFY COLUMN `ac_movement_cheat_jump_speed_change_reject` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊跳跃speed变更reject',
  MODIFY COLUMN `ac_movement_cheat_multi_jump_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊多重跳跃',
  MODIFY COLUMN `ac_movement_cheat_multi_jump_reject` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊多重跳跃reject',
  MODIFY COLUMN `ac_movement_cheat_wall_climb_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊墙面攀爬',
  MODIFY COLUMN `ac_movement_cheat_wall_climb_reject` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊墙面攀爬reject',
  MODIFY COLUMN `ac_movement_cheat_unreachable_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊不可达',
  MODIFY COLUMN `ac_movement_cheat_fly_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊飞行',
  MODIFY COLUMN `ac_movement_cheat_fly_reject` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊飞行reject',
  MODIFY COLUMN `ac_movement_cheat_no_fall_time_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊不下落时间',
  MODIFY COLUMN `ac_movement_cheat_no_fall_time_reject` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊不下落时间reject',
  MODIFY COLUMN `ac_movement_cheat_teleport_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊传送',
  MODIFY COLUMN `ac_movement_cheat_teleport_reject` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊传送reject',
  MODIFY COLUMN `ac_movement_cheat_tele_to_transport_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊传送TO载具',
  MODIFY COLUMN `ac_movement_cheat_tele_to_transport_reject` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊传送TO载具reject',
  MODIFY COLUMN `ac_movement_cheat_fake_transport_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊伪造载具',
  MODIFY COLUMN `ac_movement_cheat_water_walk_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊水上行走',
  MODIFY COLUMN `ac_movement_cheat_water_walk_reject` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊水上行走reject',
  MODIFY COLUMN `ac_movement_cheat_slow_fall_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊慢下落',
  MODIFY COLUMN `ac_movement_cheat_slow_fall_reject` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊慢下落reject',
  MODIFY COLUMN `ac_movement_cheat_hover_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊悬浮',
  MODIFY COLUMN `ac_movement_cheat_hover_reject` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊悬浮reject',
  MODIFY COLUMN `ac_movement_cheat_fixed_z_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊固定Z轴',
  MODIFY COLUMN `ac_movement_cheat_fixed_z_reject` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊固定Z轴reject',
  MODIFY COLUMN `ac_movement_cheat_root_move_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊定身move',
  MODIFY COLUMN `ac_movement_cheat_root_move_reject` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊定身movereject',
  MODIFY COLUMN `ac_movement_cheat_self_root_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊自身定身',
  MODIFY COLUMN `ac_movement_cheat_self_root_reject` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项：AC移动作弊自身定身reject',
  MODIFY COLUMN `ac_movement_cheat_wrong_ack_data_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊错误确认数据',
  MODIFY COLUMN `ac_movement_cheat_pending_ack_delay_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊待处理确认延迟',
  MODIFY COLUMN `ac_movement_cheat_explore_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊探索',
  MODIFY COLUMN `ac_movement_cheat_explore_high_level_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊探索高等级',
  MODIFY COLUMN `ac_movement_cheat_forbidden_area_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用AC移动作弊禁止区域',
  MODIFY COLUMN `ac_warden_win_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用Windows端Warden',
  MODIFY COLUMN `ac_warden_osx_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用macOS端Warden',
  MODIFY COLUMN `ac_warden_players_only` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Warden是否仅检查玩家',
  MODIFY COLUMN `ac_antispam_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用反垃圾聊天',
  MODIFY COLUMN `ac_antispam_ban_enabled` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '反垃圾聊天是否启用封禁',
  MODIFY COLUMN `ac_antispam_merge_all_whispers` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '反垃圾聊天是否合并所有密语',
  MODIFY COLUMN `visibility_force_active_objects` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否强制对象保持激活可见',
  MODIFY COLUMN `ptr` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否为测试服模式',
  MODIFY COLUMN `gm_start_on_gm_island` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'GM是否出生在GM岛',
  MODIFY COLUMN `item_log_restore_quest_items` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '物品恢复是否包含任务物品',
  MODIFY COLUMN `enforced_english` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否强制英语',
  MODIFY COLUMN `sea_network` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用SEA网络规则',
  MODIFY COLUMN `backup_character_inventory` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否备份角色背包',
  MODIFY COLUMN `analysis_stop_on_correct_extended_data` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '分析系统在扩展数据正确时是否停止',
  MODIFY COLUMN `analysis_do_shared_data_detailed_report` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '分析系统是否输出共享数据详细报告',
  MODIFY COLUMN `analysis_allow_relaxed_ip` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '分析系统是否允许宽松IP判定',
  MODIFY COLUMN `analysis_log_discord_summary` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '分析系统是否记录Discord摘要',
  MODIFY COLUMN `analysis_ping_on_warning` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '分析系统告警时是否提醒',
  MODIFY COLUMN `analysis_automatic_punihsment` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '分析系统是否自动处罚',
  MODIFY COLUMN `suspicious_enable` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用可疑行为检测',
  MODIFY COLUMN `suspicious_movement_enable` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用可疑移动检测',
  MODIFY COLUMN `suspicious_fishing_enable` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用可疑钓鱼检测',
  MODIFY COLUMN `suspicious_npc_killed_enable` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用异常NPC击杀检测',
  MODIFY COLUMN `login_region_queue` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用区域登录排队',
  MODIFY COLUMN `enable_priority_queue` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用优先排队',
  MODIFY COLUMN `priority_queue_enable_western_priority` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用西方地区优先排队',
  MODIFY COLUMN `enable_dynamic_visibilities` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用动态可视距离',
  MODIFY COLUMN `priority_queue_enable_ip_penalty` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用IP惩罚优先队列',
  MODIFY COLUMN `load_locales` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否加载本地化文本',
  MODIFY COLUMN `enable_faction_balance` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用阵营平衡',
  MODIFY COLUMN `block_all_hanzi` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否屏蔽所有汉字',
  MODIFY COLUMN `holiday_event` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用节日事件',
  MODIFY COLUMN `performance_enable` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否启用性能监控',
  COMMENT = '世界服配置缓存表（按 realm_id 存储世界服运行配置）';

-- 说明：如果当前 realm_id 在 world_config 中有记录，程序会优先读取数据库配置；
--       如果没有记录，才会回退读取 mangosd.conf，然后再把配置写回 world_config。